sudo: false

language: python

python:
   - "2.7"

before_install:
    - pip install --upgrade pip

install:
    - pip install autopep8
    - pip install coverage
    - pip install mypy
    - pip install numpy
    - pip install pylint
    - pip install -r requirements.txt

before_script:
    - uname -a
    - printenv | sort

script:
    - date
    - sh run_tests.sh