sudo: false

language: python

python:
   - "2.7"

install:
    - pip install --upgrade pip
    - pip install coverage
    - pip install -r requirements.txt

before_script:
    - uname -a
    - printenv | sort

script:
    - date
    - sh run_tests.sh