FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# brewtiful.world API
This is a rough draft of the final API, it contains the projected
API calls needed to link the front-end and back-end of the www.brewtiful.world.
We include, endpoints, response status, and requrired paramters.

## Breweries Collection [/breweries] 
 
### List All Breweries [GET]
URL:
<www.brewtiful.world/breweries>
Method : |GET|

URL Params: offset=[integer]
            limit=[integer]
            
            These paramters are used for pagination, gvies the offset (start index value),
            and the limit (how many values to get starting from offset)
            
Success Response Code: 200 + JSON Body

Returned if the API returns the right data and has 
no back end problems fetching it

Error Response Code: 500 + ERROR MESSAGE
Returned if some back-end error occurs and data is not
fetched for any reason

+ Response 200 (application/json)

        [
            {
                "state": "Texas",
                "city": "Austin",
                "name": "Adelberts",
                "established": "1982",
                "image": "/files/breweries/adelberts.jpg"
            }
        ]

+ Response 500 (application/json)

        [
            {
                "error": "INTERNAL SERVER ERROR",
               
            }
        ]

## Reviews Collection [/reviews/]

### List All Reviews [GET]
URL:
<www.brewtiful.world/reviews>
Method : |GET|

URL Params: offset=[integer]
            limit=[integer]
            
            These paramters are used for pagination, gvies the offset (start index value),
            and the limit (how many values to get starting from offset)
            
Success Response Code: 200 + JSON Body

Returned if the API returns the right data and has 
no back end problems fetching it

Error Response Code: 500 + ERROR MESSAGE
Returned if some back-end error occurs and data is not
fetched for any reason
+ Response 200 (application/json)

        [
            {
                "reviewer": "John",
                "brewery": 
                {
                "state": "Texas",
                "city" : "Austin",
                "name": "Adelberts"
                },
                "beer_name": "Mango Wit",
                "rating": "5/5"
            }
        ]
+ Response 500 (application/json)

        [
            {
                "error": "INTERNAL SERVER ERROR",
               
            }
        ]

## Beers Collection [/beers]

### List All Beers [GET]
URL:
<www.brewtiful.world/beers>
Method : |GET|

URL Params: offset=[integer]
            limit=[integer]
            
            These paramters are used for pagination, gvies the offset (start index value),
            and the limit (how many values to get starting from offset)
            
Success Response Code: 200 + JSON Body

Returned if the API returns the right data and has 
no back end problems fetching it

Error Response Code: 500 + ERROR MESSAGE
Returned if some back-end error occurs and data is not
fetched for any reason
+ Response 200 (application/json)

        [
            {
                "abv": "5.3%",
                "beer_name": "Mango Wit",
                "ibu": "3",
                "glassware": "glass cup",
                "organic": "yes",
                "price": "$$",
                "brewery": 
                    {
                    "state": "Texas",
                    "city" : "Austin",
                    "name": "Adelberts"
                    },
                "calories": "210",
                "style": "ale"
            }
        ]
+ Response 500 (application/json)

        [
            {
                "error": "INTERNAL SERVER ERROR",
               
            }
        ]

## Styles Collection [/styles]

### List All Styles [GET]
URL:
<www.brewtiful.world/styles>
Method : |GET|

URL Params: offset=[integer]
            limit=[integer]
            
            These paramters are used for pagination, gvies the offset (start index value),
            and the limit (how many values to get starting from offset)
            
Success Response Code: 200 + JSON Body

Returned if the API returns the right data and has 
no back end problems fetching it

Error Response Code: 500 + ERROR MESSAGE
Returned if some back-end error occurs and data is not
fetched for any reason
+ Response 200 (application/json)

        [
            {
                "name": "ale",
                "description": "a perfectly rich, hoppy af .... ",
                "ibu_range": "3-5",
                "abv_range": "5.5-6.2",
                "srm": "0x033F"
            }
        ]
+ Response 500 (application/json)

        [
            {
                "error": "INTERNAL SERVER ERROR",
               
            }
        ]        
## About Collection [/about]

### List Info About Team and Project [GET]
URL:
<www.brewtiful.world/about>
Method : |GET|

URL Params: offset=[integer]
            limit=[integer]
            
            These paramters are used for pagination, gvies the offset (start index value),
            and the limit (how many values to get starting from offset)
            
Success Response Code: 200 + JSON Body

Returned if the API returns the right data and has 
no back end problems fetching it

Error Response Code: 500 + ERROR MESSAGE
Returned if some back-end error occurs and data is not
fetched for any reason
+ Response 200 (application/json)

        [
            {
                "site_desc": "the purpose ....",
                "group_name": "craftHats",
                "group_members":
                [
                    {
                        "name": "Sam",
                        "photo": "/images/Sam.jpg",
                        "bio": "just a grey suit",
                        "major_responsibilities": "drank the brews",
                        "num_commits":"0",
                        "num_issues":"0",
                        "num_unit_tests":"0"
                    }
                ],
               "total_team_commits": "xxx",
               "total_team_issues": "xxxx",
               "total_team_unit_tests":"xxxx",
               "apiary_link": "www.apiary.io/crafthats",
               "github_link": "www.github.com/crafthats",
               "trello_link": "www.trello.com/crafthats",
               "data_info": 
               [
                    {
                        "resource_link": "www.resource1.com/api",
                        "resource_info": "description on how the resource was scraped"
                    }
               ],
              "tools":
              [
                    {
                        "name": "tool1",
                        "usage": " description of how it was used"
                    }
              ],
             "report_link": "utexas.app.box.com/report.pdf"
            }
            
        ]
+ Response 500 (application/json)

        [
            {
                "error": "INTERNAL SERVER ERROR",
               
            }
        ]