runtime: python27
entrypoint: gunicorn -b :$PORT main.app
threadsafe: true

runtime_config:
  python_version: 3

handlers:
- url: /
  script: main.app
#
# - url: /.*
#   script: main.app

###BEER HANDLERS
- url: /beers
  script: main.app

- url: ".*/beers/[0-9]+"
  script: main.app

- url: ".*/beers/organic/(Y|N)"
  script: main.app

- url: ".*/beers/style/.*"
  script: main.app

- url: /styles
  script: main.app

- url: ".*/styles/[0-9]+"
  script: main.app

- url: ".*/styles/srm/.*"
  script: main.app

- url: ".*/styles/abv/.*"
  script: main.app

- url: /breweries
  script: main.app

- url: ".*/breweries/[0-9]+"
  script: main.app

- url: ".*/breweries/state/.*"
  script: main.app

- url: ".*/breweries/country/.*"
  script: main.app

- url: /reviews
  script: main.app

- url: ".*/reviews/[0-9]+"
  script: main.app

libraries:
- name: MySQLdb
  version: "1.2.5"

#[START env]
env_variables:
    # Replace user, password, database, project, and instance with the values obtained
    # when configuring your Cloud SQL instance.
    SQLALCHEMY_DATABASE_URI: >-
      mysql+mysqldb://root:downing@/stagingdb?unix_socket=/cloudsql/backend-staging-183303:us-central1:stagingdb
    # SQLALCHEMY_DATABASE_URI: mysql+pymysql://root:downing@127.0.0.1/stagingdb
    # app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql+pymysql://root:downing@127.0.0.1/stagingdb'
    #

#[END env]

#[START cloudsql_settings]
# Replace project and instance with the values obtained  when configuring your
# Cloud SQL instance.
beta_settings:
    cloud_sql_instances: backend-staging-183303:us-central1:stagingdb
#[END cloudslq_settings]